### ISSUE TITLE
429 Too Many Requests, Number of allowed API requests per minute exceeded

### ISSUE THREAD

**Issue by seaxwi** [arduino/help-center-content#15]
**Summary:**
[Deploy to production workflows](https://github.com/arduino/help-center-content/actions/workflows/deploy-prod.yml) get `429 Too Many Requests, Number of allowed API requests per minute exceeded` errors and eventually fail.

![image](https://user-images.githubusercontent.com/71350948/158814020-ed791882-3454-4ec7-b224-066a66728d5e.png)

**Failed jobs:**

**[Deploy to production #19](https://github.com/arduino/help-center-content/runs/5583797275?check_suite_focus=true)**

```
time="2022-03-17T09:57:58Z" level=error msg="> update article 'My 12 month free Create plan code from the Oplá kit is not working': PUT 'https://arduino.zendesk.com/api/v2/help_center/en-us/articles/4412950847506.json' '{\"article\":{\"created_at\":\"0001-01-01T00:00:00Z\",\"updated_at\":\"0001-01-01T00:00:00Z\",\"edited_at\":\"0001-01-01T00:00:00Z\",\"user_segment_id\":null}}': 429 Too Many Requests, Number of allowed API requests per minute exceeded"
time="2022-03-17T09:57:58Z" level=error msg="> PUT 'https://arduino.zendesk.com/api/v2/help_center/en-us/articles/4412950847506.json' '{\"article\":{\"created_at\":\"0001-01-01T00:00:00Z\",\"updated_at\":\"0001-01-01T00:00:00Z\",\"edited_at\":\"0001-01-01T00:00:00Z\",\"user_segment_id\":null}}': 429 Too Many Requests, Number of allowed API requests per minute exceeded"
panic: update article 'My 12 month free Create plan code from the Oplá kit is not working': PUT 'https://arduino.zendesk.com/api/v2/help_center/en-us/articles/4412950847506.json' '{"article":{"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","edited_at":"0001-01-01T00:00:00Z","user_segment_id":null}}': 429 Too Many Requests, Number of allowed API requests per minute exceeded
```

**[Deploy to production #18](https://github.com/arduino/help-center-content/runs/5583791985?check_suite_focus=true)**

```
time="2022-03-17T09:57:57Z" level=info msg="skip content update" article="Accessing the Serial Monitor for the Arduino CLI on Windows"
time="2022-03-17T09:57:57Z" level=info msg="update content" article="Error: file does not exist, no such file or directory, system cannot find the file specified"
time="2022-03-17T09:57:57Z" level=info msg="Update article in section 360004641979: Error: file does not exist, no such file or directory, system cannot find the file specified"
time="2022-03-17T09:57:58Z" level=error msg="> GET 'https://arduino.zendesk.com/api/v2/help_center/articles/4406565090706/attachments': 429 Too Many Requests, Number of allowed API requests per minute exceeded"
panic: GET 'https://arduino.zendesk.com/api/v2/help_center/articles/4406565090706/attachments': 429 Too Many Requests, Number of allowed API requests per minute exceeded

goroutine 1 [running]:
main.must(...)
	/home/runner/work/help-center-content/help-center-content/_deploy/main.go:384
main.main()
	/home/runner/work/help-center-content/help-center-content/_deploy/main.go:80 +0x5dd
exit status 2
Error: Process completed with exit code 1.
```

**Comment by Serjlee** [comment]
Should be fixed by https://github.com/arduino/help-center-content/pull/18
